# Site settings
title: Randome Staff 
email: wallace.dyfq@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: /random/ # the subpath of your site, e.g. /blog/
url:  http://wallace-dyfq.github.io # the base hostname & protocol for your site
twitter_username: 373167780
github_username:  wallace-dyfq

# Build settings
markdown: kramdown
